Add support for explicit not tags
cypress-io/cypress-grep pull request #122
Opened 2022-04-13 08:28 UTC by pmweeks98

Add support for 'explicit not' tags.

Allows test suites with large numbers of tests and tags to set tags to not run even if other tags say to run the test

Raised this issue in #119

2022-04-15 10:52 UTC, pmweeks98 commented
Succeded workflow in forked repo
https://github.com/pmweeks98/cypress-grep/actions/runs/2172113656

2022-04-28 09:14 UTC, pmweeks98 commented
@bahmutov ping

2022-06-03 10:27 UTC, pmweeks98 commented
@bahmutov ping

2022-06-03 10:54 UTC, bahmutov approved these changes
super, looks good, let's see if all tests pass and this change will be released

2022-06-03 10:55 UTC, bahmutov requested changes
ohh @pmweeks98 can you please update the README file with this syntax?

2022-06-03 12:15 UTC, pmweeks98 commented
@bahmutov done

2022-06-03 13:11 UTC, merged